// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6RMPIv7cfMj34HphyT5l1Bdy0lwk7HMU',
    appId: '1:259673460463:web:9117f8b34f0d437d5e551a',
    messagingSenderId: '259673460463',
    projectId: 'prakflutterfirebase-7b900',
    authDomain: 'prakflutterfirebase-7b900.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-7b900.appspot.com',
    measurementId: 'G-GNW4P93M23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrSJoxkS00aAXb6iE5pgHce8AO3Rh0_40',
    appId: '1:259673460463:android:973608a0023d5a235e551a',
    messagingSenderId: '259673460463',
    projectId: 'prakflutterfirebase-7b900',
    storageBucket: 'prakflutterfirebase-7b900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtwsy2ervWhkcQUKVcQVB_JAPLLon9SJs',
    appId: '1:259673460463:ios:79da8fa8aa5d99ba5e551a',
    messagingSenderId: '259673460463',
    projectId: 'prakflutterfirebase-7b900',
    storageBucket: 'prakflutterfirebase-7b900.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtwsy2ervWhkcQUKVcQVB_JAPLLon9SJs',
    appId: '1:259673460463:ios:79da8fa8aa5d99ba5e551a',
    messagingSenderId: '259673460463',
    projectId: 'prakflutterfirebase-7b900',
    storageBucket: 'prakflutterfirebase-7b900.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6RMPIv7cfMj34HphyT5l1Bdy0lwk7HMU',
    appId: '1:259673460463:web:36d7cd91d4f349c25e551a',
    messagingSenderId: '259673460463',
    projectId: 'prakflutterfirebase-7b900',
    authDomain: 'prakflutterfirebase-7b900.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-7b900.appspot.com',
    measurementId: 'G-M2SWFLNRVD',
  );
}
